import Navbar from "@/components/Navbar";
import VS from "@/components/VS";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Solo Challenge Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <VS />
      </main>
    </>
  );
}
